// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.mopro

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_openac_mobile_app_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_openac_mobile_app_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "openac_mobile_app"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "openac_mobile_app"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_openac_mobile_app_checksum_func_build_smt_from_snapshot(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_create_smt_proof(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_create_smt_proof_from_gz(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_generate_cert_chain_rs4096_input(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_link_verify(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_mopro_hello_world(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_prove_cert_chain_rs4096(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_prove_user_sig_rs2048(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_run_complete_benchmark(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_setup_keys(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_smt_proof_to_circuit_inputs(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_verify_cert_chain_rs4096(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_verify_smt_proof(
    ): Int
    external fun uniffi_openac_mobile_app_checksum_func_verify_user_sig_rs2048(
    ): Int
    external fun ffi_openac_mobile_app_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "openac_mobile_app"))
        
    }
    external fun uniffi_openac_mobile_app_fn_func_build_smt_from_snapshot(`snapshotJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_create_smt_proof(`snapshotJson`: RustBuffer.ByValue,`keyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_create_smt_proof_from_gz(`gzData`: RustBuffer.ByValue,`keyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_generate_cert_chain_rs4096_input(`certb64`: RustBuffer.ByValue,`signedResponse`: RustBuffer.ByValue,`tbs`: RustBuffer.ByValue,`issuerCertPath`: RustBuffer.ByValue,`smtSnapshotPath`: RustBuffer.ByValue,`outputDir`: RustBuffer.ByValue,`challenge`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_link_verify(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_openac_mobile_app_fn_func_mopro_hello_world(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_prove_cert_chain_rs4096(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_prove_user_sig_rs2048(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_run_complete_benchmark(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_setup_keys(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_smt_proof_to_circuit_inputs(`proof`: RustBuffer.ByValue,`depth`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_openac_mobile_app_fn_func_verify_cert_chain_rs4096(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_openac_mobile_app_fn_func_verify_smt_proof(`proof`: RustBuffer.ByValue,`expectedRoot`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_openac_mobile_app_fn_func_verify_user_sig_rs2048(`documentsPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_openac_mobile_app_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_openac_mobile_app_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_openac_mobile_app_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_openac_mobile_app_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_openac_mobile_app_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_openac_mobile_app_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_openac_mobile_app_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_openac_mobile_app_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_openac_mobile_app_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_openac_mobile_app_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_openac_mobile_app_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_openac_mobile_app_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_openac_mobile_app_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_openac_mobile_app_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_openac_mobile_app_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_openac_mobile_app_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_openac_mobile_app_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_openac_mobile_app_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_openac_mobile_app_checksum_func_build_smt_from_snapshot() != 18712) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_create_smt_proof() != 33141) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_create_smt_proof_from_gz() != 36175) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_generate_cert_chain_rs4096_input() != 35169) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_link_verify() != 26183) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_mopro_hello_world() != 6259) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_prove_cert_chain_rs4096() != 24766) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_prove_user_sig_rs2048() != 60547) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_run_complete_benchmark() != 33093) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_setup_keys() != 30998) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_smt_proof_to_circuit_inputs() != 60154) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_verify_cert_chain_rs4096() != 22769) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_verify_smt_proof() != 5752) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openac_mobile_app_checksum_func_verify_user_sig_rs2048() != 62724) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



/**
 * Result of a complete benchmark run with timing and size metrics
 */
data class BenchmarkResults (
    var `setupMs`: kotlin.ULong
    , 
    var `proveMs`: kotlin.ULong
    , 
    var `verifyMs`: kotlin.ULong
    , 
    var `provingKeyBytes`: kotlin.ULong
    , 
    var `verifyingKeyBytes`: kotlin.ULong
    , 
    var `proofBytes`: kotlin.ULong
    , 
    var `witnessBytes`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBenchmarkResults: FfiConverterRustBuffer<BenchmarkResults> {
    override fun read(buf: ByteBuffer): BenchmarkResults {
        return BenchmarkResults(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: BenchmarkResults) = (
            FfiConverterULong.allocationSize(value.`setupMs`) +
            FfiConverterULong.allocationSize(value.`proveMs`) +
            FfiConverterULong.allocationSize(value.`verifyMs`) +
            FfiConverterULong.allocationSize(value.`provingKeyBytes`) +
            FfiConverterULong.allocationSize(value.`verifyingKeyBytes`) +
            FfiConverterULong.allocationSize(value.`proofBytes`) +
            FfiConverterULong.allocationSize(value.`witnessBytes`)
    )

    override fun write(value: BenchmarkResults, buf: ByteBuffer) {
            FfiConverterULong.write(value.`setupMs`, buf)
            FfiConverterULong.write(value.`proveMs`, buf)
            FfiConverterULong.write(value.`verifyMs`, buf)
            FfiConverterULong.write(value.`provingKeyBytes`, buf)
            FfiConverterULong.write(value.`verifyingKeyBytes`, buf)
            FfiConverterULong.write(value.`proofBytes`, buf)
            FfiConverterULong.write(value.`witnessBytes`, buf)
    }
}



/**
 * Result of a proving operation with timing and proof metadata.
 * `prove_ms` is the total time for both circuits; `proof_size_bytes` is the combined size.
 */
data class ProofResult (
    var `proveMs`: kotlin.ULong
    , 
    var `proofSizeBytes`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProofResult: FfiConverterRustBuffer<ProofResult> {
    override fun read(buf: ByteBuffer): ProofResult {
        return ProofResult(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: ProofResult) = (
            FfiConverterULong.allocationSize(value.`proveMs`) +
            FfiConverterULong.allocationSize(value.`proofSizeBytes`)
    )

    override fun write(value: ProofResult, buf: ByteBuffer) {
            FfiConverterULong.write(value.`proveMs`, buf)
            FfiConverterULong.write(value.`proofSizeBytes`, buf)
    }
}



/**
 * Circom-ready SMT inputs — all values as decimal strings, siblings padded to depth.
 * Mirrors `ecdsa_spartan2::smt_client::SmtCircuitInputs`.
 */
data class SmtCircuitInputs (
    var `smtRoot`: kotlin.String
    , 
    var `serialNumber`: kotlin.String
    , 
    var `smtSiblings`: List<kotlin.String>
    , 
    var `smtOldKey`: kotlin.String
    , 
    var `smtOldValue`: kotlin.String
    , 
    var `smtIsOld0`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSmtCircuitInputs: FfiConverterRustBuffer<SmtCircuitInputs> {
    override fun read(buf: ByteBuffer): SmtCircuitInputs {
        return SmtCircuitInputs(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SmtCircuitInputs) = (
            FfiConverterString.allocationSize(value.`smtRoot`) +
            FfiConverterString.allocationSize(value.`serialNumber`) +
            FfiConverterSequenceString.allocationSize(value.`smtSiblings`) +
            FfiConverterString.allocationSize(value.`smtOldKey`) +
            FfiConverterString.allocationSize(value.`smtOldValue`) +
            FfiConverterString.allocationSize(value.`smtIsOld0`)
    )

    override fun write(value: SmtCircuitInputs, buf: ByteBuffer) {
            FfiConverterString.write(value.`smtRoot`, buf)
            FfiConverterString.write(value.`serialNumber`, buf)
            FfiConverterSequenceString.write(value.`smtSiblings`, buf)
            FfiConverterString.write(value.`smtOldKey`, buf)
            FfiConverterString.write(value.`smtOldValue`, buf)
            FfiConverterString.write(value.`smtIsOld0`, buf)
    }
}



/**
 * SMT proof from the moica-revocation-smt server, all values as hex strings.
 */
data class SmtProof (
    /**
     * Tree root at proof time (hex string).
     */
    var `root`: kotlin.String
    , 
    /**
     * Sibling hashes from leaf level upward (hex strings).
     */
    var `siblings`: List<kotlin.String>
    , 
    /**
     * [key] for non-membership; [key, value, marker] for membership.
     */
    var `entry`: List<kotlin.String>
    , 
    /**
     * Present for non-membership proofs when a conflicting leaf exists.
     */
    var `matchingEntry`: List<kotlin.String>?
    , 
    /**
     * True if the key is claimed to exist in the tree.
     */
    var `membership`: kotlin.Boolean
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSmtProof: FfiConverterRustBuffer<SmtProof> {
    override fun read(buf: ByteBuffer): SmtProof {
        return SmtProof(
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterOptionalSequenceString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: SmtProof) = (
            FfiConverterString.allocationSize(value.`root`) +
            FfiConverterSequenceString.allocationSize(value.`siblings`) +
            FfiConverterSequenceString.allocationSize(value.`entry`) +
            FfiConverterOptionalSequenceString.allocationSize(value.`matchingEntry`) +
            FfiConverterBoolean.allocationSize(value.`membership`)
    )

    override fun write(value: SmtProof, buf: ByteBuffer) {
            FfiConverterString.write(value.`root`, buf)
            FfiConverterSequenceString.write(value.`siblings`, buf)
            FfiConverterSequenceString.write(value.`entry`, buf)
            FfiConverterOptionalSequenceString.write(value.`matchingEntry`, buf)
            FfiConverterBoolean.write(value.`membership`, buf)
    }
}





/**
 * Errors that can occur during ZK proof operations
 */
sealed class ZkProofException: kotlin.Exception() {
    
    class FileNotFound(
        
        val `msg`: kotlin.String
        ) : ZkProofException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class ProofGenerationFailed(
        
        val `msg`: kotlin.String
        ) : ZkProofException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class VerificationFailed(
        
        val `msg`: kotlin.String
        ) : ZkProofException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class InvalidInput(
        
        val `msg`: kotlin.String
        ) : ZkProofException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class SetupRequired(
        
        val `msg`: kotlin.String
        ) : ZkProofException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class IoException(
        
        val `msg`: kotlin.String
        ) : ZkProofException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ZkProofException> {
        override fun lift(error_buf: RustBuffer.ByValue): ZkProofException = FfiConverterTypeZkProofError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeZkProofError : FfiConverterRustBuffer<ZkProofException> {
    override fun read(buf: ByteBuffer): ZkProofException {
        

        return when(buf.getInt()) {
            1 -> ZkProofException.FileNotFound(
                FfiConverterString.read(buf),
                )
            2 -> ZkProofException.ProofGenerationFailed(
                FfiConverterString.read(buf),
                )
            3 -> ZkProofException.VerificationFailed(
                FfiConverterString.read(buf),
                )
            4 -> ZkProofException.InvalidInput(
                FfiConverterString.read(buf),
                )
            5 -> ZkProofException.SetupRequired(
                FfiConverterString.read(buf),
                )
            6 -> ZkProofException.IoException(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ZkProofException): ULong {
        return when(value) {
            is ZkProofException.FileNotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ZkProofException.ProofGenerationFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ZkProofException.VerificationFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ZkProofException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ZkProofException.SetupRequired -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ZkProofException.IoException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: ZkProofException, buf: ByteBuffer) {
        when(value) {
            is ZkProofException.FileNotFound -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ZkProofException.ProofGenerationFailed -> {
                buf.putInt(2)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ZkProofException.VerificationFailed -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ZkProofException.InvalidInput -> {
                buf.putInt(4)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ZkProofException.SetupRequired -> {
                buf.putInt(5)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ZkProofException.IoException -> {
                buf.putInt(6)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalSequenceString: FfiConverterRustBuffer<List<kotlin.String>?> {
    override fun read(buf: ByteBuffer): List<kotlin.String>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterSequenceString.read(buf)
    }

    override fun allocationSize(value: List<kotlin.String>?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterSequenceString.allocationSize(value)
        }
    }

    override fun write(value: List<kotlin.String>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterSequenceString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}
        /**
         * Parse a @zk-kit/smt v1.0.2-compatible snapshot JSON and return its root.
         *
         * The returned root can be used as `expected_root` in subsequent calls to
         * `verify_smt_proof`.
         */ fun `buildSmtFromSnapshot`(`snapshotJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_build_smt_from_snapshot(
    
        
        FfiConverterString.lower(`snapshotJson`),_status)
}
    )
    }
    

        /**
         * Load a snapshot and generate a proof for `key_hex` in one call (JSON input).
         *
         * # Arguments
         * * `snapshot_json` – decompressed snapshot JSON string
         * * `key_hex`       – certificate serial number as a hex string (with or without `0x`)
         *
         * Returns the proof ready to pass straight into `verify_smt_proof`.
         */
    @Throws(ZkProofException::class) fun `createSmtProof`(`snapshotJson`: kotlin.String, `keyHex`: kotlin.String): SmtProof {
            return FfiConverterTypeSmtProof.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_create_smt_proof(
    
        
        FfiConverterString.lower(`snapshotJson`),
        FfiConverterString.lower(`keyHex`),_status)
}
    )
    }
    

        /**
         * Load a snapshot and generate a proof for `key_hex` in one call (gzip input).
         *
         * # Arguments
         * * `gz_data` – raw bytes of the `.json.gz` snapshot file
         * * `key_hex` – certificate serial number as a hex string (with or without `0x`)
         *
         * Returns the proof ready to pass straight into `verify_smt_proof`.
         */
    @Throws(ZkProofException::class) fun `createSmtProofFromGz`(`gzData`: kotlin.ByteArray, `keyHex`: kotlin.String): SmtProof {
            return FfiConverterTypeSmtProof.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_create_smt_proof_from_gz(
    
        
        FfiConverterByteArray.lower(`gzData`),
        FfiConverterString.lower(`keyHex`),_status)
}
    )
    }
    

        /**
         * Generate split circuit inputs for both cert_chain_rs4096 and user_sig_rs2048.
         *
         * Writes two JSON files into `output_dir`:
         * - `cert_chain_rs4096_input.json`
         * - `user_sig_rs2048_input.json`
         *
         * These are the input files expected by `prove` via `PathConfig::mobile`.
         *
         * `smt_proof` should be the non-membership proof for the certificate's serial
         * number, produced by `create_smt_proof_from_gz` / `create_smt_proof`.
         * Pass `None` to omit SMT revocation checking.
         */
    @Throws(ZkProofException::class) fun `generateCertChainRs4096Input`(`certb64`: kotlin.String, `signedResponse`: kotlin.String, `tbs`: kotlin.String, `issuerCertPath`: kotlin.String, `smtSnapshotPath`: kotlin.String?, `outputDir`: kotlin.String, `challenge`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_generate_cert_chain_rs4096_input(
    
        
        FfiConverterString.lower(`certb64`),
        FfiConverterString.lower(`signedResponse`),
        FfiConverterString.lower(`tbs`),
        FfiConverterString.lower(`issuerCertPath`),
        FfiConverterOptionalString.lower(`smtSnapshotPath`),
        FfiConverterString.lower(`outputDir`),
        FfiConverterString.lower(`challenge`),_status)
}
    )
    }
    

        /**
         * Verify proofs for cert_chain_rs4096 and user_sig_rs2048 circuits.
         */
    @Throws(ZkProofException::class) fun `linkVerify`(`documentsPath`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_link_verify(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    

        /**
         * Test function for basic UniFFI integration
         */ fun `moproHelloWorld`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_mopro_hello_world(
    
        _status)
}
    )
    }
    

        /**
         * Generate proofs for cert_chain_rs4096 circuit.
         *
         * Reads input JSONs via `PathConfig::mobile(documents_path)`:
         * - `{documents_path}/cert_chain_rs4096_input.json`
         *
         * Writes proofs, instances, and witnesses under `{documents_path}/keys/`.
         *
         * Witnesses are pre-warmed before any Spartan2 key I/O so that witnesscalc's
         * C++ realloc runs on a clean heap and avoids macOS SIGSEGV from moved pointers.
         */
    @Throws(ZkProofException::class) fun `proveCertChainRs4096`(`documentsPath`: kotlin.String): ProofResult {
            return FfiConverterTypeProofResult.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_prove_cert_chain_rs4096(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    

        /**
         * Generate proofs for both cert_chain_rs4096 and user_sig_rs2048 circuits.
         *
         * Reads input JSONs via `PathConfig::mobile(documents_path)`:
         * - `{documents_path}/cert_chain_rs4096_input.json`
         * - `{documents_path}/user_sig_rs2048_input.json`
         *
         * Writes proofs, instances, and witnesses under `{documents_path}/keys/`.
         *
         * Witnesses are pre-warmed before any Spartan2 key I/O so that witnesscalc's
         * C++ realloc runs on a clean heap and avoids macOS SIGSEGV from moved pointers.
         */
    @Throws(ZkProofException::class) fun `proveUserSigRs2048`(`documentsPath`: kotlin.String): ProofResult {
            return FfiConverterTypeProofResult.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_prove_user_sig_rs2048(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    

        /**
         * Run complete benchmark pipeline for both cert_chain_rs4096 and user_sig_rs2048 circuits.
         *
         * Witnesses are pre-warmed on a clean heap before Spartan2 setup to prevent macOS SIGSEGV:
         * witnesscalc's C++ `realloc()` moves large allocations on a fragmented heap, leaving stale
         * interior pointers. Pre-warming ensures the realloc happens before heap fragmentation.
         * Each circuit is then processed in isolation (setup → save → drop PK → prove → verify) to
         * avoid holding two large proving keys in memory simultaneously. Timings and sizes are combined.
         */
    @Throws(ZkProofException::class) fun `runCompleteBenchmark`(`documentsPath`: kotlin.String): BenchmarkResults {
            return FfiConverterTypeBenchmarkResults.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_run_complete_benchmark(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    

        /**
         * Setup circuit keys for both cert_chain_rs4096 and user_sig_rs2048.
         *
         * Requires that `{documents_path}/certChainRS4096.r1cs` and
         * `{documents_path}/userSigRS2048.r1cs` are present.
         */
    @Throws(ZkProofException::class) fun `setupKeys`(`documentsPath`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_setup_keys(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    

        /**
         * Convert an `SmtProof` (hex strings) into the `SmtCircuitInputs` that the
         * Circom cert-chain circuit expects (decimal strings, siblings padded to `depth`).
         *
         * This is the offline equivalent of `ecdsa_spartan2::smt_client::fetch_smt_proof`:
         * instead of hitting the server you supply the proof generated from the local snapshot.
         */
    @Throws(ZkProofException::class) fun `smtProofToCircuitInputs`(`proof`: SmtProof, `depth`: kotlin.UInt): SmtCircuitInputs {
            return FfiConverterTypeSmtCircuitInputs.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_smt_proof_to_circuit_inputs(
    
        
        FfiConverterTypeSmtProof.lower(`proof`),
        FfiConverterUInt.lower(`depth`),_status)
}
    )
    }
    

        /**
         * Verify proofs for cert_chain_rs4096 circuit.
         */
    @Throws(ZkProofException::class) fun `verifyCertChainRs4096`(`documentsPath`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_verify_cert_chain_rs4096(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    

        /**
         * Verify an SMT non-membership (or membership) proof against a trusted root.
         *
         * Recomputes the Merkle root from `proof.entry` + `proof.siblings` using
         * Poseidon-P256, then compares against `expected_root`.  Returns `true` iff
         * the proof is valid.
         */ fun `verifySmtProof`(`proof`: SmtProof, `expectedRoot`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_verify_smt_proof(
    
        
        FfiConverterTypeSmtProof.lower(`proof`),
        FfiConverterString.lower(`expectedRoot`),_status)
}
    )
    }
    

        /**
         * Verify proofs for user_sig_rs2048 circuit.
         */
    @Throws(ZkProofException::class) fun `verifyUserSigRs2048`(`documentsPath`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(ZkProofException) { _status ->
    UniffiLib.uniffi_openac_mobile_app_fn_func_verify_user_sig_rs2048(
    
        
        FfiConverterString.lower(`documentsPath`),_status)
}
    )
    }
    


